### ISSUE TITLE
npm start fails with (cannot find busboy)

### ISSUE THREAD

**Issue by serialdoom** [seejohnrun/haste-server#120]
Here is the error log

```
haste-server_1 | npm info it worked if it ends with ok
haste-server_1 | npm info using npm@3.8.6
haste-server_1 | npm info using node@v6.1.0
haste-server_1 | npm info lifecycle haste@0.1.0~prestart: haste@0.1.0
haste-server_1 | npm info lifecycle haste@0.1.0~start: haste@0.1.0
haste-server_1 | 
haste-server_1 | > haste@0.1.0 start /haste
haste-server_1 | > node server.js
haste-server_1 | 
haste-server_1 | module.js:440
haste-server_1 |     throw err;
haste-server_1 |     ^
haste-server_1 | 
haste-server_1 | Error: Cannot find module 'busboy'
haste-server_1 |     at Function.Module._resolveFilename (module.js:438:15)
haste-server_1 |     at Function.Module._load (module.js:386:25)
haste-server_1 |     at Module.require (module.js:466:17)
haste-server_1 |     at require (internal/module.js:20:19)
haste-server_1 |     at Object.<anonymous> (/haste/lib/document_handler.js:2:14)
haste-server_1 |     at Module._compile (module.js:541:32)
haste-server_1 |     at Object.Module._extensions..js (module.js:550:10)
haste-server_1 |     at Module.load (module.js:456:32)
haste-server_1 |     at tryModuleLoad (module.js:415:12)
haste-server_1 |     at Function.Module._load (module.js:407:3)
haste-server_1 | 
haste-server_1 | npm info lifecycle haste@0.1.0~start: Failed to exec start script
haste-server_1 | npm ERR! Linux 3.19.0-15-generic
haste-server_1 | npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
haste-server_1 | npm ERR! node v6.1.0
haste-server_1 | npm ERR! npm  v3.8.6
haste-server_1 | npm ERR! code ELIFECYCLE
haste-server_1 | npm ERR! haste@0.1.0 start: `node server.js`
haste-server_1 | npm ERR! Exit status 1
haste-server_1 | npm ERR! 
haste-server_1 | npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
haste-server_1 | npm ERR! Make sure you have the latest version of node.js and npm installed.
haste-server_1 | npm ERR! If you do, this is most likely a problem with the haste package,
haste-server_1 | npm ERR! not with npm itself.
haste-server_1 | npm ERR! Tell the author that this fails on your system:
haste-server_1 | npm ERR!     node server.js
haste-server_1 | npm ERR! You can get information on how to open an issue for this project with:
haste-server_1 | npm ERR!     npm bugs haste
haste-server_1 | npm ERR! Or if that isn't available, you can get their info via:
haste-server_1 | npm ERR!     npm owner ls haste
haste-server_1 | npm ERR! There is likely additional logging output above.
haste-server_1 | 
haste-server_1 | npm ERR! Please include the following file with any support request:
haste-server_1 | npm ERR!     /haste/npm-debug.log
```

with `/hast/npm-debug.log` being:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle haste@0.1.0~prestart: haste@0.1.0
6 silly lifecycle haste@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle haste@0.1.0~start: haste@0.1.0
8 verbose lifecycle haste@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle haste@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/haste/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle haste@0.1.0~start: CWD: /haste
11 silly lifecycle haste@0.1.0~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle haste@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle haste@0.1.0~start: Failed to exec start script
14 verbose stack Error: haste@0.1.0 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid haste@0.1.0
16 verbose cwd /haste
17 error Linux 3.19.0-15-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.1.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error haste@0.1.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the haste@0.1.0 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the haste package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs haste
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls haste
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Unfortunately i have no idea about npm/node so im not sure what to make of that log.

**Comment by XaoticLabs** [comment]
try "npm install" in that directory and try again
