### ISSUE TITLE
Error while trying to run

### ISSUE THREAD

**Issue by PassageDev** [seejohnrun/haste-server#163]
Hi so I'm trying to run the server on my ovh vps, I seem to get some sort of error when I perform `npm start`

Here is the output: https://gist.github.com/PassageDev/2e868afbb71ceeec4f8e6a3a8b2752a8

Please could you help me fix this error, I would aprichiate it, thanks Josh.

**Comment by seejohnrun** [comment]
What version of `node` are you using? Also how are you starting the server? (what command)

**Comment by blysik** [comment]
Same error here:

2 info using npm@5.3.0
3 info using node@v8.4.0

```
$ more /Users/blysik/.npm/_logs/2017-09-07T20_53_57_945Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pastebin@0.1.0~prestart: pastebin@0.1.0
6 info lifecycle pastebin@0.1.0~start: pastebin@0.1.0
7 verbose lifecycle pastebin@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pastebin@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/blysik/Documents/git/orchard-apps/hastebin/node_modules/.bin:/Users/blysik/.rbenv/shims:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/appleinternal/bin:/opt/apple/bin:/usr/local/MacGPG2/bin:/Users/blysik/Library/Python/2.7/bin:/Users/blysik/.rvm/bin
9 verbose lifecycle pastebin@0.1.0~start: CWD: /Users/blysik/Documents/git/orchard-apps/hastebin
10 silly lifecycle pastebin@0.1.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle pastebin@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle pastebin@0.1.0~start: Failed to exec start script
13 verbose stack Error: pastebin@0.1.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid pastebin@0.1.0
15 verbose cwd /Users/blysik/Documents/git/orchard-apps/hastebin
16 verbose Darwin 16.5.0
17 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error pastebin@0.1.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the pastebin@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by blysik** [comment]
I'm just doing 'npm start' after 'npm install'.

**Comment by blysik** [comment]
Here's the npm start:

```
$ npm start

> pastebin@0.1.0 start /Users/blysik/Documents/git/hastebin
> node server.js

info: using predefined redis client

/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:271
        throw new JS_Parse_Error(message, line, col, pos);
        ^
Error
    at new JS_Parse_Error (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:263:22)
    at js_error (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:271:15)
    at croak (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:732:17)
    at token_error (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:739:17)
    at unexpected (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:745:17)
    at /Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:1123:17
    at maybe_unary (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:1208:27)
    at expr_ops (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:1235:32)
    at maybe_conditional (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:1239:28)
    at maybe_assign (/Users/blysik/Documents/git/hastebin/node_modules/uglify-js/lib/parse-js.js:1263:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pastebin@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pastebin@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/blysik/.npm/_logs/2017-09-07T20_56_56_163Z-debug.log
```

**Comment by seejohnrun** [comment]
@blysik what is `pastebin`?

**Comment by Logic-gate** [comment]
@blysik clone a clean version, dont change anything, and then try again.

**Comment by blysik** [comment]
Sorry, yes.  This is probably related to a rename to work within a private PaaS.  Let me try a clean version.
