### ISSUE TITLE
npm install OK, npm start FAILED

### ISSUE THREAD

**Issue by geekism** [seejohnrun/haste-server#184]
It fails on CentOS 6.5 And Debian 8 x86_64

[root@quassel:/var/www/hastebin]# npm start

> haste@0.1.0 start /var/www/hastebin
> node server.js

info: configuring redis
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md

/var/www/hastebin/lib/key_generators/phonetic.js:3
const randOf = (collection) => {
                             ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/hastebin/server.js:90:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 8
npm ERR! not ok code 0
[root@quassel:/var/www/hastebin]# 

it installs, and runs fine in Debian 9.

**Comment by geekism** [comment]
I upgraded my node/npm to 8.5.1. And redid the install, and reissued the start. Resolved my problem.

**Comment by Logic-gate** [comment]
Closing the issue.

Cheers,
