### ISSUE TITLE
haste-server won't start

### ISSUE THREAD

**Issue by HerrTxbias** [seejohnrun/haste-server#195]
Hello! I have the following issue: If i want to start the haste server i get this error:
```
root@fsn1:/opt/haste-server# npm start

> haste@0.1.0 start /opt/haste-server
> node server.js

info: configuring redis
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
/opt/haste-server/lib/key_generators/phonetic.js:13
module.exports = class PhoneticKeyGenerator {
                 ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/haste-server/server.js:90:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.13.13-4-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs haste
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/haste-server/npm-debug.log
root@fsn1:/opt/haste-server#
```

Hope somebody can help me with that.

Thank you!

**Comment by seejohnrun** [comment]
Looks like you'll need to upgrade node.js
