### ISSUE TITLE
Error with memcached as storage 

### ISSUE THREAD

**Issue by lgunnar** [seejohnrun/haste-server#201]
I tried to use a storage setting of

{
    "type": "memcached",
    "host": "127.0.0.1",
    "port": 11211,
    "expire": 864000
  },

but it resulted in the error

util.js:969
    throw new TypeError('The super constructor to "inherits" must not ' +
    ^

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.inherits (util.js:969:11)
    at Object.<anonymous> (/usr/local/haste-server/node_modules/memcache/lib/memcache.js:45:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/haste-server/lib/document_stores/memcached.js:1:79)

Is there a bug or did I miss something

**Comment by seejohnrun** [comment]
@lgunnar Thanks for the report! I've implemented https://github.com/seejohnrun/haste-server/pull/203 to handle this issue with the `memcache` dependency.  If that works for you, I can likely merge it in tonight
