### ISSUE TITLE
NPM start: Unexpected Reserved Word

### ISSUE THREAD

**Issue by ghost** [seejohnrun/haste-server#240]
nodejs v10.8.0

When running npm install I get these warns

```

npm WARN engine mocha@4.1.0: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine growl@1.10.3: wanted: {"node":">=4.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine supports-color@4.4.0: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})

```

When I run npm start I get the following:

```
REDACTED@REDACTED:/var/www/html/haste$ npm start

> haste@0.1.0 start /var/www/html/haste
> node server.js

/var/www/html/haste/lib/document_stores/memcached.js:4
class MemcachedDocumentStore {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/www/html/haste/server.js:52:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 4.4.0-127-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/haste/npm-debug.log

```

NPM-Debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart haste@0.1.0
6 info start haste@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info haste@0.1.0 Failed to exec start script
9 verbose stack Error: haste@0.1.0 start: `node server.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/np$
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/np$
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:10$
10 verbose pkgid haste@0.1.0
11 verbose cwd /var/www/html/haste
12 error Linux 4.4.0-127-generic
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error haste@0.1.0 start: `node server.js`
17 error Exit status 1
18 error Failed at the haste@0.1.0 start script 'node server.js'.
18 error This is most likely a problem with the haste package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node server.js
18 error You can get their info via:
18 error     npm owner ls haste
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

**Comment by seejohnrun** [comment]
You;'ll need to use a more modern version of `node`
