### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by Jerlag01** [seejohnrun/haste-server#255]
I'm getting the following note when trying to start the haste server.
jerlag@FC-linux1:~/haste-server$ npm start

> haste@0.1.0 start /home/jerlag/haste-server
> node server.js

/home/jerlag/haste-server/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/home/jerlag/haste-server/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/home/jerlag/haste-server/node_modules/winston/lib/winston/logger.js:245:9)
    at Object.winston.(anonymous function).args [as add] (/home/jerlag/haste-server/node_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/home/jerlag/haste-server/server.js:31:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Anyone know how to fix this?

**Comment by seejohnrun** [comment]
Can you please paste your config ?

**Comment by Jerlag01** [comment]
here is my config:
https://pastebin.com/Zt7p4YT3
