### ISSUE TITLE
Fresh install following instructions yields npm ERR! haste@0.1.0 start: `node server.js`

### ISSUE THREAD

**Issue by MostHated** [seejohnrun/haste-server#260]
Below is the log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle haste@0.1.0~prestart: haste@0.1.0
6 info lifecycle haste@0.1.0~start: haste@0.1.0
7 verbose lifecycle haste@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle haste@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/haste/haste-server/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/.pyenv/bin:/snap/bin
9 verbose lifecycle haste@0.1.0~start: CWD: /root/haste/haste-server
10 silly lifecycle haste@0.1.0~start: Args: [ '-c', 'node server.js' ]
11 silly lifecycle haste@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle haste@0.1.0~start: Failed to exec start script
13 verbose stack Error: haste@0.1.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid haste@0.1.0
15 verbose cwd /root/haste/haste-server
16 verbose Linux 4.4.0-137-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.12.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error haste@0.1.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the haste@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Just to see, I tried to start it also using just 'node server.js start' and it came up with this.

```
/haste/haste-server# node server.js start
/root/haste/haste-server/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/root/haste/haste-server/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/root/haste/haste-server/node_modules/winston/lib/winston/logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (/root/haste/haste-server/node_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/root/haste/haste-server/server.js:31:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

```

Thanks,
-MH

**Comment by MostHated** [comment]
Hey there, no info on this?

**Comment by bionichuman** [comment]
@MostHated Friend me on discord and maybe I can help you. 

BionicHuman
#3200

**Comment by robertparkerx** [comment]
Did you get a fix for this? I am having the same problem on a fresh install.

**Comment by MostHated** [comment]
I lost interest in trying quickly after I posted this. Hopefully whatever it was is fixed by now, lol.

**Comment by seejohnrun** [comment]
Please see https://github.com/seejohnrun/haste-server/issues/280#issuecomment-704635885 / If anyone comes up with more details on a new version please reach out
