### ISSUE TITLE
Problem with start after install!

### ISSUE THREAD

**Issue by jimmyr57000** [seejohnrun/haste-server#272]
Hello, 

I have a problem with start hasteserver.. i'am use ubuntu !

`root@Personnel:/home/haste-server# npm start

> haste@0.1.0 start /home/haste-server
> node server.js

/home/haste-server/lib/document_stores/memcached.js:4
class MemcachedDocumentStore {
^^^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/haste-server/server.js:52:11)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)

npm ERR! Linux 4.15.18-7-pve
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "start"
npm ERR! node v2.5.0
npm ERR! npm  v2.13.2
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/haste-server/npm-debug.log
You have mail in /var/mail/root
root@Personnel:/home/haste-server# `

**Comment by webmastir** [comment]
Looks like you need to upgrade node.js.
