### ISSUE TITLE
selfhosted: Not saving document

### ISSUE THREAD

**Issue by PrincessRavy** [seejohnrun/haste-server#273]
On pressing save or ctrl+s nothing is saved.

# Setup
## Server
OS: Ubuntu 18.04.1 LTS "bionic beaver"
Web Server: nginx 1.15.7 (built with OpenSSL 1.1.1b-dev)
Node.js: 8.10.0 (npm 3.5.2)
Haste: 0.1.0 (latest)

## Configuration
Haste
```json
{
  "host": "0.0.0.0",
  "port": 7777,
  "keyLength": 10,
  "maxLength": 400000,
  "staticMaxAge": 86400,
  "recompressStaticAssets": true,
  "logging": [
    {
      "level": "verbose",
      "type": "Console",
      "colorize": true
    }
  ],
  "keyGenerator": {
    "type": "phonetic"
  },
  "rateLimits": {
    "categories": {
      "normal": {
        "totalRequests": 500,
        "every": 60000
      }
    }
  },
  "storage": {
    "type": "memcached",
    "host": "127.0.0.1",
    "port": 11211,
    "expire": 2592000
  },
  "documents": {
    "about": "./about.md"
  }
}
```

Nginx:
using ssl, http2
- some stuff omitted due to not being relevant or privacy
```
server {
    location / {
        proxy_pass http://localhost:7777/;
    }
}
```

# Logs
## Browser
```
cards-click.js:145  get full word
cards-click.js:150  textNode <body data-gr-c-s-loaded=​"true" style>​…​</body>​
documents:1         Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
jquery.min.js:4     POST https://haste.farfrom.earth/documents 500 (Internal Server Error)
documents:1         Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
```

## Haste-server
stdout:
```
0|haste    | info: connecting to memcached on 127.0.0.1:11211
0|haste    | info: compressed application.js into application.min.js
0|haste    | info: loading static document name=about, path=./about.md
0|haste    | info: listening on 0.0.0.0:7777
0|haste    | verbose: error adding document
0|haste    | verbose: error adding document
0|haste    | verbose: error adding document
0|haste    | warn: document not found key=documents
0|haste    | verbose: error adding document
```

stderr:
```
0|haste    | debug: loaded static document success=false
0|haste    | TypeError: Cannot read property 'replace' of undefined
0|haste    |     at Object.exports.escapeValue (/var/www/<url>/node_modules/memcached/lib/utils.js:152:16)
0|haste    |     at Client.setters (/var/www/<url>/node_modules/memcached/lib/memcached.js:929:19)
0|haste    |     at Client.bowlofcurry [as set] (/var/www/<url>/node_modules/memcached/lib/utils.js:126:15)
0|haste    |     at MemcachedDocumentStore.set (/var/www/<url>/lib/document_stores/memcached.js:29:17)
0|haste    |     at Client.client.get (/var/www/haste.farfrom.earth/lib/document_stores/memcached.js:41:14)
0|haste    |     at Client.memcached.makeCallback (/var/www/<url>/node_modules/memcached/lib/memcached.js:693:11)
0|haste    |     at Client.memcachedCommand [as command] (/var/www/<url>/node_modules/memcached/lib/memcached.js:306:42)
0|haste    |     at Client.get (/var/www/<url>/node_modules/memcached/lib/memcached.js:830:10)
0|haste    |     at MemcachedDocumentStore.get (/var/www/<url>/lib/document_stores/memcached.js:36:17)
0|haste    |     at DocumentHandler.handleGet (/var/www/<url>/lib/document_handler.js:20:14)
```

**Comment by mathieu-aubin** [comment]
proxy_pass http://localhost:7777/;

0|haste    | info: listening on 0.0.0.0:7777

localhost doesn't equal 0.0.0.0

**Comment by wickedlizerd** [comment]
Any update on how to fix this? Having this issue myself.

**Comment by mathieu-aubin** [comment]
0.0.0.0:7777 doesnt equal localhost:7777
localhost is more than likely 127.0.0.1 and
0.0.0.0 would (again likely) be the publically available ip address of the server.

change your haste config to listen on 127.0.0.1 not 0.0.0.0 and retry

**Comment by wickedlizerd** [comment]
Yes, while OP should change their host, that’s clearly not the issue at hand. His instance is clearly getting the save request, as per “verbose: error adding document”. See my edit in my comment above for a workaround to OP’s issue.

**Comment by Nekiono** [comment]
So memcached is the villain? Will try and confirm later.
