### ISSUE TITLE
Can't start server with memcached on Raspberry Pi

### ISSUE THREAD

**Issue by MayusYT** [seejohnrun/haste-server#282]
I can't start the server on my raspberry pi 3 b +  when I enable the `memcached` storage option. This is the start log:
```
root@raspberrypi:/home/pi/haste-server# npm start
(node:7163) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> haste@0.1.0 start /home/pi/haste-server
> node server.js

undefined:34
  {
  ^

SyntaxError: Unexpected token { in JSON at position 432
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/pi/haste-server/server.js:14:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/haste-server
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/haste-server/npm-debug.log
npm ERR! not ok code 0
```

**Comment by MayusYT** [comment]
Turns out my config file was broken.
