### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by opanopan** [seejohnrun/haste-server#284]
It crashes when i come to the wrong address. Log has entries:
warn: document not found key=esuzarokuc
/home/hastebin/haste-server/node_modules/memcached/lib/utils.js:152
  return value.replace(/(\r|\n)/g, '\\$1');
               ^

TypeError: Cannot read property 'replace' of undefined
    at Object.exports.escapeValue (/home/hastebin/haste-server/node_modules/memcached/lib/utils.js:152:16)
    at Client.setters (/home/hastebin/haste-server/node_modules/memcached/lib/memcached.js:929:19)
    at Client.bowlofcurry [as set] (/home/hastebin/haste-server/node_modules/memcached/lib/utils.js:126:15)
    at MemcachedDocumentStore.set (/home/hastebin/haste-server/lib/document_stores/memcached.js:29:17)
    at Object.client.get [as callback] (/home/hastebin/haste-server/lib/document_stores/memcached.js:41:14)
    at Client.memcached.delegateCallback (/home/hastebin/haste-server/node_modules/memcached/lib/memcached.js:687:12)
    at Client.rawDataReceived (/home/hastebin/haste-server/node_modules/memcached/lib/memcached.js:758:22)
    at Client.BufferBuffer (/home/hastebin/haste-server/node_modules/memcached/lib/memcached.js:678:12)
    at Socket.bowlofcurry (/home/hastebin/haste-server/node_modules/memcached/lib/utils.js:126:15)
    at Socket.emit (events.js:182:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hastebin/.npm/_logs/2019-03-26T07_22_55_408Z-debug.log

**Comment by extragornax** [comment]
Any update?

**Comment by asiudoisjdfo** [comment]
Looking for an update as well? :-)
