### ISSUE TITLE
Memcached not found

### ISSUE THREAD

**Issue by Brian-Graham** [seejohnrun/haste-server#288]
Pulled from the repo then tried to start the haste-server and I get this error:

```
> haste@0.1.0 start /var/www/vhosts/**domain**/hastebin
> node server.js

module.js:478
    throw err;
    ^

Error: Cannot find module 'memcached'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/vhosts/**domain**/hastebin/lib/document_stores/memcached.js:1:81)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)

npm ERR! Linux 4.2.8
npm ERR! argv "/opt/plesk/node/6/bin/node" "/opt/plesk/node/6/bin/npm" "run" "start"
npm ERR! node v6.14.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs haste
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.
```

**Comment by RealBlackB1RD** [comment]
npm i memcached --save

**Comment by phpjsnerd** [comment]
Or you can use the just plain file system. Edit the config.js file like this.
https://github.com/seejohnrun/haste-server/blob/master/config.js
```javascript
{

  "host": "0.0.0.0",
  "port": 7777,

  "keyLength": 10,

  "maxLength": 400000,

  "staticMaxAge": 86400,

  "recompressStaticAssets": true,

  "logging": [
    {
      "level": "verbose",
      "type": "Console",
      "colorize": true
    }
  ],

  "keyGenerator": {
    "type": "phonetic"
  },

  "rateLimits": {
    "categories": {
      "normal": {
        "totalRequests": 500,
        "every": 60000
      }
    }
  },

  "storage": {
  "path": "./data",
  "type": "file"
  },

  "documents": {
    "about": "./about.md"
  }

}
```
