### ISSUE TITLE
CERT_UNTRUSTED

### ISSUE THREAD

**Issue by finki70** [seejohnrun/haste-server#292]
```
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1357:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:970:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:463:15)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:219:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:209:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.9.0-8-amd64
npm ERR! command "/root/.nvm/v0.10.17/bin/node" "/root/.nvm/v0.10.17/bin/npm" "i                                                                                                             nstall"
npm ERR! cwd /home/users/hosting/www/haste/haste-server
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/users/hosting/www/haste/haste-server/npm-debug.log
npm ERR! not ok code 0
```

This happened on Debian.

**Comment by lynxgian** [comment]
you need to run npm set strict-ssl false
