### ISSUE TITLE
Error: listen EADDRNOTAVAIL: address not available **.**.***.**:7777

### ISSUE THREAD

**Issue by Pxrple** [seejohnrun/haste-server#296]
```cmd
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 71.59.127.198:7777
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL: address not available **.**.***.**:7777
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ty\AppData\Roaming\npm-cache\_logs\2019-07-08T22_22_27_904Z-debug.log
```

**Comment by Pxrple** [comment]
The log: https://hasteb.in/lotujapo.kotlin

**Comment by seejohnrun** [comment]
You likely have two versions of hastebin running at the same time
