### ISSUE TITLE
Some Error with logging

### ISSUE THREAD

**Issue by MaxWarsNicht** [seejohnrun/haste-server#310]
I will leave the console log below. Somehow I got a problem there...

> /root/node/haste-server/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/root/node/haste-server/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/root/node/haste-server/node_modules/winston/lib/winston/logger.js:345:11)
    at Object.winston.<computed> [as add] (/root/node/haste-server/node_modules/winston/lib/winston.js:110:68)
    at Object.<anonymous> (/root/node/haste-server/server.js:31:13)
    at Module._compile (internal/modules/cjs/loader.js:1196:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:10)
    at Module.load (internal/modules/cjs/loader.js:1045:32)
    at Function.Module._load (internal/modules/cjs/loader.js:949:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: node server.js

**Comment by seejohnrun** [comment]
What do you have in your config as the logging area?
