### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Owned67** [seejohnrun/haste-server#325]
`npm start

> haste@0.1.0 start F:\haste-server-master
> node server.js

info: connecting to memcached on 127.0.0.1:11211
info: compressed application.js into application.min.js
info: loading static document name=about, path=./about.md
info: listening on 192.168.1.15:7777
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 192.168.1.15:7777
    at Server.setupListenHandle [as _listen2] (net.js:1260:19)
    at listenInCluster (net.js:1325:12)
    at doListen (net.js:1458:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at emitErrorNT (net.js:1304:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haste@0.1.0 start script.
npm ERR! This is probably not a problem with
[2020-06-09T21_10_01_418Z-debug.log](https://github.com/seejohnrun/haste-server/files/4754874/2020-06-09T21_10_01_418Z-debug.log)
 npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alpha\AppData\Roaming\npm-cache\_logs\2020-06-09T21_10_01_418Z-debug.log`

OS: WIndows 10 x64

cmd prompt with admin right

**Comment by Owned67** [comment]
Solved
