### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by the4ndy** [seejohnrun/haste-server#99]
I get the below error when trying to run npm start.

```
> haste@0.1.0 start /root/haste-server
> node server.js

/root/haste-server/node_modules/connect/node_modules/qs/lib/index.js:5
const Stringify = require('./stringify');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/haste-server/node_modules/connect/lib/middleware/bodyParser.js:13:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 4.2.2-1-pve
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! haste@0.1.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the haste@0.1.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the haste package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls haste
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/haste-server/npm-debug.log
```

Also, attached is the npm-debug.log file as requested by the above output
[npm-debug.log.txt](https://github.com/seejohnrun/haste-server/files/48106/npm-debug.log.txt)

**Comment by wraithgar** [comment]
See https://github.com/seejohnrun/haste-server/issues/97
